app = "n8n-deploy"
primary_region = "iad" # المنطقة: Virginia, US

[build]
  dockerfile = "./Dockerfile"

[env]
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "admin"
  N8N_BASIC_AUTH_PASSWORD = "yourStrongPassword"
  N8N_HOST = "0.0.0.0"
  N8N_PORT = "5678"
  DB_TYPE = "mongodb"
  DB_MONGODB_CONNECTION_URL = "mongodb+srv://<username>:<password>@<cluster-url>/<db>?retryWrites=true&w=majority"

[[services]]
  internal_port = 5678
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
